### ISSUE TITLE
Cannot render multiple markers on the map in MapView and React Native - Error: Text strings must be rendered within a <text> component

### ISSUE THREAD

**Issue by IliasMariosG** [IliasMariosG/OilWellsEarthquakes#3]
### Environment
- OS: MacOS Catalina 10.15.6
- expo-cli
- "expo": "~38.0.9"
- "react-native": "~0.62.2"
- node version: v14.4.0
- Shell: zsh

### What I am trying to do
- I am trying to render multiple markers on the map.

- The markers are essentially the latitude ("LAT") and longitude ("LONG") found inside the InjectionWells.json file.

- The map is loaded, but the markers are not rendered. 
### What the error says:
- After around a minute, I get an error saying:

> `Error: Text strings must be rendered within a <text> component`
>> This error is located at:`
>> in AIRMAP (at MapView.js:994)
>> in MapView (at App.js:10)
>> in RCTView (at App.js:9)
>> in App (created by ExpoRoot)
>> in RCTView (at NativeAppearance.tsx:4)
>> in FallbackAppearanceProvider (at src/index.tsx:70)
>> in AppearanceProvider (created by ExpoRoot)
>> in RootErrorBoundary (created by ExpoRoot)
>> in ExpoRoot (at render Applications.js:45)
>> in RCTView (at AppContainer.js:109)
>> in RCTView (at AppContainer.js:135)
>> in AppContainer (at render Application.js: 39)

#### My understanding 
is that the conditional rendering is not made correctly. Probably the presence of null values in the .json file makes the code where the `filter` and `map` methods are a bit complicated. However, I'm not really sure how to get past this. The solutions I have seen online have to do with cases where react fragments and conditional renderings do not deal with null values in the .json. 
If you need anything else, let me know. Thank you.

### Code
     `import React from 'react';
      import MapView, { Marker } from 'react-native-maps';
      import { StyleSheet, Text, View, Dimensions, Image } from 'react-native';
      import oilWells from './oilWells/InjectionWells.json';

     export default class App extends React.Component {
       render() {
       return (
        <View style={styles.container}>
          <MapView
            initialRegion={{
              latitude: 36.9003240,
              longitude: -98.2182600,
              latitudeDelta: 0.01,
              longitudeDelta: 5,
            }}
            [style={styles.mapStyle} >

              {oilWells.filter(oilwell => 
                (oilwell["LAT"]!== null) && (oilwell["LONG"]!==null)).map((oilwell) => {
                return (<Marker key={oilwell["API#"]} coordinate={{ latitude: oilwell["LAT"], longitude: 
                  oilwell["LONG"] }}>
                <Image source={require('./assets/oil-well-marker.png')} style={styles.markerImage} />
                </Marker>);
              })}; 
            </MapView>   
          </View>
        );
      }
    }
    const styles = StyleSheet.create({
     container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
      },
      mapStyle: {
        width: Dimensions.get('window').width,
        height: Dimensions.get('window').height,
      },
      markerImage: {
        width: 30,
        height: 30,
      },
    });`

**Comment by wider2** [comment]
good afternoon
i have exactly the same mistake when try to show markers on the map
how did you solved it anyway?
